config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies, 
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.by_position
    order("position ASC")
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolios, only: [:edit, :show, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.by_position
  end

  def new 
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: "Your portfolio item is now live." }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def show
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio Item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: "Portfolio item was successfully removed" }
    end
  end

  private

  def set_portfolios
    @portfolio_item = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image, :position, technologies_attributes: [:name, :id, :_destroy])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file
          <%= form.file_field :main_image, style: "display:none;" %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file
          <%= form.file_field :thumb_image, style: "display:none;" %>
        </label>
      </div>

      <div class="form-group">
        <%= form.label :position %>
        <%= form.number_field :position, class: "form-control" %>
      </div>
    </div>

     <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", rows: "10" %>
      </div>
    </div>
  </div>
  <hr>
  <div class="col-md-12">
  <h2>Technolgies Used</h2>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'Add Technology', form, :technologies %>
      </div>
      <%# <%= form.fields_for :technologies do |technology_form| %>
        <%# <div class="form-group"> %>
          <%# <%= technology_form.label :name %> 
          <%# <%= technology_form.text_field :name, class: "form-control" %>
        <%# </div> %>
      <%# <% end %>
    </div>

    <div class="form-group">
      <%= form.submit "Save Portfolio Item", class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card">
  <%= image_tag portfolio_img(portfolio_item.thumb_image.url, 'thumb') %>
  <p class="card-text">
    <span>
      <%= link_to portfolio_item.title, portfolio_path(portfolio_item) %>
    </span>
    <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association "Remove Technology", f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h2>Edit this portfolio item</h2>

  <%= render "portfolios/form", item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <%= link_to 'New Portfolio', new_portfolio_path if logged_in?(:site_admin) %>
    <div class="row sortable">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h2>Create a new Portfolio</h2>
  <%= render "portfolios/form", item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.thumb_image.url, 'main') %>
    </div>

    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <% if logged_in?(:site_admin) %>
        <%= link_to 'Delete Portfolio', @portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <hr>
      <em><%= @portfolio_item.subtitle %></em><br/><br/>
      <p><%= @portfolio_item.body %></p>

      <h3>Technologies Used:</h3>
      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div class="col-md-12">
          <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>