config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot app-footer">
  <div class="inner">
    <p><%= @copyright %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix zIndex">
  <div class="inner">
    <a href="<%= root_path %>"><h3 class="masthead-brand">Zack Martin</h3></a>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper "nav-link", "span"%>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= @copyright %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper "nav-link", "span"%>
      <%= login_helper "nav-link" %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><%= fa_icon "github" %></li>
      <li><%= fa_icon "linkedin" %></li>
      <li><%= fa_icon "instagram" %></li>
    </ol>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
  <%# <div><%= link_to "Blog", blogs_path %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p><%= @copyright %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">More recent case studies of my work can be reviewed in an in-person or virtual interview.</p>
    <p>
      <%= link_to "Find Out More About Me", about_path, class:"btn btn-primary" %>
      <%= link_to "Resume (.pdf)", "https://docs.google.com/document/d/e/2PACX-1vRcs7rMlVKfF5hM7rrMLm4taV4LApm-vuF22oahFNMeQY3XAYOL7cgMsMcBofnmAP3Qv-fZrSZ6EU7K/pub", class:"btn btn-secondary", target: "_blank" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse navbar-dark bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">Hey there!</h4>
        <p class="text-muted">I’m Zack Martin and I’m a Software Engineer with a background in visual design, web development, and data analysis. I have a passion for improving innovative & intuitive experiences in an iterative process by looking at what is already out there and working (and not working), monitoring qualitative & quantitative analytics, and improving interactions based on user feedback.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper "text-white", "li" %>
          <li><%= login_helper "text-white" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark">
  <div class="container d-flex justify-content-between">
    <a href="<%= root_path %>" class="navbar-brand">Zack Martin</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>